name: Tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      http_proxy:
        required: false
        description: http proxy e.g "http://0.0.0.0:8000"
      https_proxy:
        required: false
        description: https proxy e.g "http://0.0.0.0:8000"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Unit Tests
        run: python -m unittest
        env:
          HTTP_PROXY: ${{ inputs.http_proxy || vars.HTTP_PROXY }}
          HTTPS_PROXY: ${{ inputs.https_proxy || vars.HTTPS_PROXY }}

